2024-05-29 11:46:50,291:ERROR:An unexpected error occurred: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\mcveydb\\AppData\\Local\\Temp\\tmp3ncwwakg\\test123\\2024_test123\\Working\\test123.gdb\\_gdb.D266027.4860.27244.sr.lock'
2024-05-29 11:47:33,324:ERROR:An unexpected error occurred: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\mcveydb\\AppData\\Local\\Temp\\tmpoorz45r4\\test1232\\2024_test1232\\Working\\test1232.gdb\\_gdb.D266027.4860.27244.sr.lock'
2024-05-29 16:04:46,688:ERROR:An unexpected error occurred: create_project() missing 1 required positional argument: 'root'
2024-05-29 16:05:37,026:ERROR:An unexpected error occurred: create_project() missing 1 required positional argument: 'root'
2024-05-30 12:13:22,175:ERROR:CURRENT
2024-05-30 12:30:20,023:ERROR:Failed to execute. Parameters are not valid.
ERROR 000732: Output Geodatabase: Dataset P:\PROJECTS\2024Proj\2024_asdfasdf\data\CAD.gdb does not exist or is not supported
ERROR 000735: Dataset: Value is required
ERROR 000532: A valid reference scale value must be set
Failed to execute (CADToGeodatabase).

2024-05-30 12:32:38,071:ERROR:'NoneType' object is not iterable
2024-05-30 13:58:41,821:ERROR:'NoneType' object is not iterable
2024-05-31 09:41:39,079:ERROR:Valid project name is required.
2024-05-31 09:41:53,666:ERROR:Failed to execute. Parameters are not valid.
ERROR 000732: Output Geodatabase: Dataset P:\PROJECTS\2024Proj\2024_jijijij\data\architectural_example-imperial.gdb does not exist or is not supported
ERROR 000735: Dataset: Value is required
ERROR 000532: A valid reference scale value must be set
Failed to execute (CADToGeodatabase).

2024-06-07 13:39:52,704:ERROR:Valid project name is required.
2024-06-07 16:04:15,556:ERROR:'NoneType' object is not iterable
2024-06-07 16:10:16,893:ERROR:'NoneType' object is not iterable
2024-06-07 16:17:38,816:ERROR:'NoneType' object is not iterable
2024-06-07 16:27:42,069:ERROR:'NoneType' object is not iterable
2024-06-07 16:30:17,358:ERROR:'NoneType' object is not iterable
